---
- name: MMN Packages - List of packages to be installed
  debug:
    var: packages_install is truthy
- name: MMN Packages - Installing packages non OpenWrt
  ansible.builtin.package:
    name: "{{ packages_install }}"
    state: present
  when:
    - packages_install is truthy
    - ansible_packages_is_openwrt is not truthy or
      (ansible_packages_pkg_manager is defined and ansible_packages_pkg_manager != "opkg" and
       ansible_packages_pkg_manager != "apk")
    - not packages_runimagebuilder | default(false) | bool
- name: MMN Packages - Installing packages OpenWrt (opkg)
  ansible.builtin.opkg:
    name: "{{ packages_install | join(packages_separator) }}"
    state: present
    update_cache: true
  when:
    - packages_install is truthy
    - ansible_distribution == 'OpenWrt' or ansible_distribution == 'LEDE'
    - ansible_packages_is_openwrt is truthy and
      (ansible_packages_pkg_manager is defined and ansible_packages_pkg_manager == "opkg")
    - not packages_runimagebuilder | default(false) | bool
- name: MMN Packages - Installing packages OpenWrt (apk)
  ansible.builtin.apk:
    name: "{{ packages_install | join(packages_separator) }}"
    state: present
    update_cache: true
  when:
    - packages_install is truthy
    - ansible_packages_is_openwrt is truthy and
      (ansible_packages_pkg_manager is defined and ansible_packages_pkg_manager == "apk")
    - not packages_runimagebuilder | default(false) | bool
