---
- name: MMN Packages - Detect OpenWrt package manager
  include_tasks: "0detect-pkg-manager.yml"
  when: (packages_runimagebuilder | default(false)) is not truthy and
        ansible_distribution is defined and
        (ansible_distribution == 'OpenWrt' or
         (ansible_distribution | regex_search('Wrt|LEDE', ignorecase=True) is truthy))
        or ansible_distribution is not defined

- name: MMN Packages - Prepare install variables
  include_tasks: "1prepare_install.yml"

- name: MMN Packages - Prepare install variables
  include_tasks: "2prepare_remove.yml"

- name: MMN Packages - Updating caches if possible
  include_tasks: "3cache.yml"
  when: ( packages_runimagebuilder is not defined ) or
        ( packages_runimagebuilder is defined and not packages_runimagebuilder | default(false) | bool )

- name: MMN Packages - Remove tasks
  include_tasks: "4remove.yml"

- name: MMN Packages - Install tasks
  include_tasks: "5install.yml"

